### ISSUE TITLE
Box data does NOT contain the right BOX_NAME identifier

### ISSUE THREAD

**Issue by AllThatIsTheCase** [philsmd/vap11g#7]
I'm getting an error when I try to configure my vap11g. What can you make of the log at https://gist.github.com/ea04656d1ac4b5e2cf4f ?

**Comment by philsmd** [comment]
Hey.
The log is not very clear to me, for instance why is there no "sudo"... which parameters do you use
-v -d should be used for debugging

When I try to use:
./vap11g.py -v -d
I have this in the output:
[i] Box data:
0001 BOX_NAME:VAP11G
0002 MAC_ADDR:00....

In the log I don't see this "BOX_NAME:VAP11G" identifier and afaik it is required for a successfull connection.

Maybe the only problem is that you do not use root.

Also, does this happen every time or only from time to time?
Did you try to reconnect your device, but the interface up and run sudo ./vap11g.py again?
thx

**Comment by philsmd** [comment]
I troubleshooted this problem now in more details.
In fact, also here if I put the interface up and immediately try to connect to the device, it sometimes reports invalid BOX_NAME.

For me this patch a1eda9864 fixed it. Can you please test if it works for you too?

**Comment by AllThatIsTheCase** [comment]
I'm getting "It seems that the device did not accept your configuration: status code was: 80, will reboot anyway". This was after I booted that system into single user mode; in regular runlevel, I still got the error above, and with debug on I saw all kinds of traffic passing by generated by regular daemons.

**Comment by philsmd** [comment]
Please confirm following points:
1. did configuring your VAP11G not work at all with vap11g.py, or does it show this errors occassionaly but not every time
2. did you try with the windows software ? (to exclude that there is some sort of hardware failure)
3. did you make sure you run it as described in README.md? With root permission etc...

If you don't mind, it would be also great if you can give more details about your setup (operating system etc).

Maybe you should also try to use a different setup + ubuntu 14.10 operating system (also live cd should work) such that we can exclude that the OS is the problem etc.

My device is btw a blue VAP11G-300 (on the back it says "HW Ver: 5.0.0), maybe you have a different version (VAP11g-500) which may expects a different sequence of packets (dunno).
Can you confirm that your hardware version is that same as mine?

Please answer all of the above questions.
Thx

**Comment by AllThatIsTheCase** [comment]
Yeah, sorry, I should have done that immediately:

1. I have not been able to get it to work at all
2. I tried with the windows software and after some googling I found a version that worked with Win8/64bit. I have been able to set the config. This config did also show up in the debug logs, BTW
3. I did always run with sudo, except when I tried in single user mode, when I had a root shell after boot. I have tried on two separate systems, one with a live usb ubuntu 14.10, one installed 14.10 headless system. I tried the single user mode on the installed system.

Even on windows it took a couple of tries before the config "took", so perhaps this device is just flaky. Why they didn't just expose the config as a file over USB...

**Comment by AllThatIsTheCase** [comment]
Device: blue VAP11G, HW: Ver: 5.0.0

**Comment by philsmd** [comment]
Thanks for the info.

Unfortunately I have no further idea what the problem could be. It is also very difficult for me to troubleshoot/debug the problem without the (your) device (maybe you can try to do that?).
You can for instance "sniff" the packets with wireshark etc and see what the windows software does differently. (but this is exactly what I did and the protocol should be correct since it works perfectly here with my device(s))

Are you sure that every connector (usb + ethernet cable) is correctly connected? Since the programming of the device is done over the ethernet interface, it must be connected and the interface must be up (maybe try to shut the interface down and up again etc)
Also always try to connect the device directly to your lan port, i.e. make sure that no other devices/switches are connected to the lan port, because this could give some conflicts.

If nothing helps, maybe you can try to get a new VAP11g device and test with that one?

**Comment by AllThatIsTheCase** [comment]
Yep, all connected directly to the LAN port, and no other interfaces
active. I'll get a second one, they're not expensive on DX.

**Comment by philsmd** [comment]
Hey.
I tried to troubleshoot this problem even further also because I sometimes noticed (after I investigated this issue a little bit) that my device does sometimes report some responses from the device that do not make sense. Yes, sometimes even here it happens (happened) that the device says wrong BOX_NAME.

So what I did with latest commit fee1c4a1c0d764b27e07819b2861d98cc80e9f95:
1. mac filtering, it seems that all VAP11g have a MAC address starting with 00:17:13:... (also your device see: https://gist.github.com/anonymous/ea04656d1ac4b5e2cf4f )
2. in your log I also noticed (after looking at it more careful) that there are several broadcasts ( starting with ff ff ff ff ff ff coming in as *responses*), I changed the code such that the broadcast will be send as it was before, but incoming broadcasts will be ignored (because we do not want to have them conflicting with the actual traffic/messages)
3. once a device with a valid mac was recognised (as said all VAP11g IMO should start with 00:17:13), that specific destination MAC address and our local lan MAC address will be used for the *whole* conversation, this is enforced by the new read () function that always makes sure that no other MAC addresses will be used for the communication with the device

All those points should make the conversation much more stable and conflicting / garbage traffic hopefully won't conflict anymore

Can you please try again with latest code?
Thx

**Comment by AllThatIsTheCase** [comment]
Super, I'll try when I get home.

**Comment by philsmd** [comment]
did you have any chance to test the latest version of vap11g.py ?
In the meantime I did commit other changes (for mac OS X support etc). Those commits shouldn't be a problem for this issue (BOX_NAME not found etc).
But still, both changes did involve a large amount of code changes.

It would be great if you can try latest code. It should work. If not, please try also the version before the OS X support commit.
Thx

**Comment by philsmd** [comment]
I will close this issue since it seems to be fixed.

If not and you still experience some problems, please reopen this issue.
Thx
